/**
 * A tenant admin's request to have an adaptive course generated by AI.
 *
 * Building a whole course is the platform's largest single LLM spend, and the model quota is
 * SHARED across every tenant — so one admin re-running a build a few times degrades generation
 * for all of them. The tenant-side "Generate with AI" click therefore files one of these instead
 * of starting work, and nothing is spent until it is approved here.
 */

export type CourseRequestStatus = 'pending' | 'approved' | 'rejected';

export const COURSE_REQUEST_STATUS_LABELS: Record<CourseRequestStatus, string> = {
  pending: 'Awaiting review',
  approved: 'Approved',
  rejected: 'Rejected',
};

export const COURSE_REQUEST_STATUS_TONE: Record<CourseRequestStatus, string> = {
  pending: 'bg-amber-500/10 text-amber-600 border-amber-500/30',
  approved: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/30',
  rejected: 'bg-rose-500/10 text-rose-600 border-rose-500/30',
};

export interface CourseRequestBrief {
  title: string;
  description: string;
  target_audience: string;
  duration_weeks: number;
}

/** What approving this actually commissions — the reviewer's whole reason for being here. */
export interface CourseRequestScale {
  weeks: number;
  submodules: number;
  content_types: string[];
  estimated_items: number;
}

export interface CourseRequestListItem {
  id: number;
  job_id: string;
  approval_status: CourseRequestStatus;
  status: string;
  created_at: string;
  client: { id: number; name: string; slug?: string } | null;
  requested_by: { id: number | null; name: string; email: string };
  brief: CourseRequestBrief;
  requested_note: string;
  review_note: string;
  reviewed_at: string | null;
  reviewed_by: string | null;
  scale: CourseRequestScale;
  /** Non-empty when a reviewer edited the brief, so the requester sees what changed. */
  edited_fields: string[];
}

export interface CourseRequestDetail extends CourseRequestListItem {
  config: Record<string, unknown>;
  original_brief: Partial<CourseRequestBrief>;
}

export interface CourseRequestListResponse {
  results: CourseRequestListItem[];
  total: number;
  offset: number;
  limit: number;
  pending_count: number;
}
